name: pyoti
channels:
  - anaconda
  - default
dependencies:
  - python=3.9.*
  - numpy
  - scipy
  - cython=0.29.*
  - make
  - cmake
  - pip
  - ipykernel
  - conda-forge::pyvista
  - conda-forge::gmsh
  - conda-forge::python-gmsh
  - conda-forge::vtk
  - conda-forge::scikit-sparse
  - conda-forge::scikit-umfpack
